# Configuration for Gemini 2.0 Flash with 10 samples
# This configuration uses Google's Gemini 2.0 Flash model for multimodal misinformation detection

name: gemini_flash_10_samples
description: Gemini 2.0 Flash configuration with 10 samples for MMFakeBench evaluation

# Model configuration
model:
  name: gemini-2.0-flash-exp
  api_key: $GEMINI_API_KEY
  temperature: 0.2
  max_retries: 3
  additional_params:
    max_tokens: 1000

# Dataset configuration
dataset:
  type: custom
  data_path: ../data/MMFakeBench/MMFakeBench_test.json
  params:
    images_base_dir: ../data/MMFakeBench/MMFakeBench_test
    limit: 10  # Process only 10 samples
    shuffle: true
    validation_split: 0.1

# Pipeline configuration
pipeline:
  - type: preprocessing
    name: preprocessor
    config:
      image_resize: true
      max_image_size: 1024
      text_cleaning: true
      normalize_text: true
      clean_text: true
      normalize_unicode: true
      remove_html: true
      lowercase: false
      max_text_length: 5000

  - type: validation
    name: validator
    config:
      strict_mode: false
      check_image_format: true
      check_text_length: true
      max_text_length: 5000
      min_text_length: 1
      allowed_image_formats: ['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp']
      max_image_size: 10485760  # 10MB

  - type: detection
    name: detector
    config:
      llm_provider: gemini
      model_name: gemini-2.0-flash-exp
      prompt_template: baseline
      include_reasoning: true
      confidence_threshold: 0.5
      max_retries: 3
      retry_delay: 1.0
      timeout: 30

# Output configuration
output:
  format: json
  save_path: results/gemini_flash_10_samples_results.json
  include_metadata: true
  save_intermediate: false

# Logging configuration
logging:
  level: INFO
  file: logs/gemini_flash_10_samples.log
  console: true
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

# Evaluation configuration
evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
    - confusion_matrix
  save_results: true
  results_path: results/gemini_flash_10_samples_evaluation.json